"use client";

import { motion } from "framer-motion";
import Image from "next/image";
import {
  Building2,
  LayoutGrid,
  FileText,
  Boxes,
  ListChecks,
  Code2,
  ShieldCheck,
  History,
  Users,
  Lock,
  MessageSquare,
  Activity,
  Bell,
  Rocket,
  Target,
  Smile,
  FlaskConical,
  Bot,
  Settings,
  Share2,
  BarChart3,
  Star,
  Plus,
  FileCode,
  Database as DatabaseIcon,
  type LucideIcon,
} from "lucide-react";

const fade = {
  hidden: { opacity: 0, y: 24 },
  show: { opacity: 1, y: 0 },
};

const features: { icon: LucideIcon; title: string; desc: string }[] = [
  { icon: Building2, title: "Multi-Tenant Organizations", desc: "Manage multiple organizations with complete data isolation, role-based access, and enterprise controls." },
  { icon: LayoutGrid, title: "Product Workspaces", desc: "Create unlimited products. Everything organized in one place—PRDs, architecture, tasks, code, and tests." },
  { icon: FileText, title: "AI PRD Generation", desc: "Turn ideas into detailed PRDs in minutes. AI analyzes, structures, and generates comprehensive documents." },
  { icon: Boxes, title: "Architecture Design", desc: "AI Architect creates scalable system designs, diagrams, and tech stacks tailored to your requirements." },
  { icon: ListChecks, title: "Task & Sprint Management", desc: "AI breaks down work into actionable tasks, plans sprints, assigns agents, and tracks progress in real-time." },
  { icon: Code2, title: "AI Code Generation", desc: "Production-ready code generated by AI Developers with best practices, standards, and clean architecture." },
  { icon: ShieldCheck, title: "QA & Test Automation", desc: "AI QA Engineer creates test plans, manual test cases, and automated tests to ensure high quality." },
  { icon: History, title: "Version & Change Tracking", desc: "Every artifact is versioned. Track changes, compare versions, and maintain a complete history." },
];

const pills: { icon: LucideIcon; label: string }[] = [
  { icon: Users, label: "Real-time Collaboration" },
  { icon: Lock, label: "Role Based Access" },
  { icon: MessageSquare, label: "Comments & Mentions" },
  { icon: Activity, label: "Activity Feeds" },
  { icon: Bell, label: "Notifications" },
];

const stats: { icon: LucideIcon; value: string; label: string }[] = [
  { icon: Rocket, value: "10x", label: "Faster Development" },
  { icon: Target, value: "90%", label: "Less Manual Work" },
  { icon: Smile, value: "100%", label: "Visibility & Control" },
];

const progress = [
  { label: "PRD", value: 100, color: "#22c55e" },
  { label: "Architecture", value: 100, color: "#22c55e" },
  { label: "Tasks", value: 72, color: "#7c3aed" },
  { label: "Code", value: 66, color: "#3b82f6" },
  { label: "QA", value: 40, color: "#f59e0b" },
];

const agents = [
  { who: "AI PM", act: "Created PRD", time: "2h ago", color: "#7c3aed" },
  { who: "AI Architect", act: "Generated architecture", time: "5h ago", color: "#3b82f6" },
  { who: "AI Team Lead", act: "Created 42 tasks", time: "8h ago", color: "#06b6d4" },
  { who: "AI Developer", act: "Completed 18 tasks", time: "1d ago", color: "#f59e0b" },
  { who: "AI QA Engineer", act: "Generated 32 test cases", time: "30m ago", color: "#22c55e" },
];

const modules = [
  { name: "User Management", value: 100, color: "#22c55e" },
  { name: "Lead Management", value: 80, color: "#3b82f6" },
  { name: "Deal Management", value: 60, color: "#7c3aed" },
  { name: "Analytics Dashboard", value: 40, color: "#06b6d4" },
  { name: "Notifications", value: 20, color: "#f59e0b" },
];

const artifacts: { name: string; ver: string; time: string; icon: LucideIcon }[] = [
  { name: "AI CRM PRD", ver: "v2.1", time: "2h ago", icon: FileText },
  { name: "System Architecture", ver: "v1.3", time: "5h ago", icon: Boxes },
  { name: "Database Schema", ver: "v1.2", time: "8h ago", icon: DatabaseIcon },
  { name: "API Specification", ver: "v1.0", time: "1d ago", icon: FileCode },
  { name: "Test Plan", ver: "v1.0", time: "1d ago", icon: FlaskConical },
];

function ViewAll() {
  return <span className="text-[9px] font-medium text-brand">View all</span>;
}

/* ───────────────────────── dashboard mockup ───────────────────────── */
function DashboardMock() {
  const nav: [string, LucideIcon][] = [
    ["Organizations", Building2],
    ["Products", LayoutGrid],
    ["PRDs", FileText],
    ["Architecture", Boxes],
    ["Tasks", ListChecks],
    ["Test Cases", FlaskConical],
    ["AI Agents", Bot],
    ["Reports", BarChart3],
    ["Settings", Settings],
  ];
  return (
    <div className="flex h-full flex-col overflow-hidden rounded-2xl border border-card-border bg-card shadow-[0_40px_100px_-44px_var(--glow)]">
      <div className="flex flex-1">
        {/* sidebar */}
        <div className="hidden w-40 shrink-0 flex-col justify-between border-r border-card-border bg-card-2/40 p-3 md:flex">
          <div>
            <div className="flex items-center gap-2 px-1">
              <Image src="/operixa-cube.png" alt="" width={18} height={18} className="h-[18px] w-[18px]" />
              <span className="text-[12px] font-bold tracking-wide text-foreground">OPERIXA</span>
            </div>
            <div className="mt-4 space-y-0.5">
              {nav.map(([l, Icon], i) => (
                <div
                  key={l}
                  className={`flex items-center gap-2 rounded-lg px-2.5 py-1.5 text-[10.5px] font-medium ${
                    i === 1 ? "bg-brand/15 text-brand" : "text-muted"
                  }`}
                >
                  <Icon size={13} />
                  {l}
                </div>
              ))}
            </div>
          </div>
          <div className="flex items-center gap-2 border-t border-card-border pt-2.5">
            <span className="grid h-7 w-7 place-items-center rounded-full bg-gradient-to-br from-violet-500 to-blue-500 text-[10px] font-bold text-white">A</span>
            <div className="leading-tight">
              <div className="text-[10px] font-semibold text-foreground">Alex Johnson</div>
              <div className="text-[9px] text-muted">Product Manager</div>
            </div>
          </div>
        </div>

        {/* main */}
        <div className="flex min-w-0 flex-1 flex-col p-4">
          {/* topbar */}
          <div className="flex items-center justify-between">
            <div className="text-[10px] text-muted">Products › AI CRM Platform</div>
            <div className="flex items-center gap-2">
              <div className="flex -space-x-1.5">
                {["#7c3aed", "#3b82f6", "#06b6d4"].map((c) => (
                  <span key={c} className="h-5 w-5 rounded-full border-2 border-card" style={{ background: c }} />
                ))}
              </div>
              <span className="inline-flex items-center gap-0.5 rounded-lg border border-card-border px-2 py-1 text-[10px] font-medium text-muted">
                <Plus size={10} /> Invite
              </span>
              <span className="inline-flex items-center gap-1 rounded-lg bg-brand px-2.5 py-1 text-[10px] font-semibold text-brand-foreground">
                <Share2 size={10} /> Share
              </span>
            </div>
          </div>
          <div className="mt-2 flex items-center gap-1.5">
            <span className="text-base font-bold text-foreground">AI CRM Platform</span>
            <Star size={13} className="fill-amber-400 text-amber-400" />
          </div>
          <div className="mt-2 flex gap-4 border-b border-card-border pb-2 text-[10.5px]">
            {["Overview", "PRD", "Architecture", "Tasks", "QA", "Files", "Activity"].map((tb, i) => (
              <span key={tb} className={i === 0 ? "font-semibold text-brand" : "text-muted"}>{tb}</span>
            ))}
          </div>

          {/* row 1 */}
          <div className="mt-3 grid flex-1 gap-3 sm:grid-cols-2">
            {/* project progress */}
            <div className="rounded-xl border border-card-border bg-card-2/50 p-3">
              <div className="text-[10.5px] font-semibold text-foreground">Project Progress</div>
              <div className="mt-2 flex items-center gap-3">
                <div className="relative h-14 w-14 shrink-0">
                  <svg viewBox="0 0 48 48" className="h-14 w-14 -rotate-90">
                    <circle cx="24" cy="24" r="20" fill="none" stroke="var(--border)" strokeWidth="5" />
                    <circle cx="24" cy="24" r="20" fill="none" stroke="#7c3aed" strokeWidth="5" strokeLinecap="round" strokeDasharray="125.6" strokeDashoffset="35" />
                  </svg>
                  <div className="absolute inset-0 grid place-items-center text-center leading-none">
                    <span>
                      <span className="block text-[12px] font-bold text-foreground">72%</span>
                      <span className="block text-[7px] text-muted">Complete</span>
                    </span>
                  </div>
                </div>
                <div className="flex-1 space-y-1">
                  {progress.map((p) => (
                    <div key={p.label} className="flex items-center gap-1.5 text-[9px]">
                      <span className="h-1.5 w-1.5 rounded-full" style={{ background: p.color }} />
                      <span className="flex-1 text-foreground/75">{p.label}</span>
                      <span className="font-medium text-muted">{p.value}%</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* agent activity */}
            <div className="rounded-xl border border-card-border bg-card-2/50 p-3">
              <div className="flex items-center justify-between">
                <span className="text-[10.5px] font-semibold text-foreground">AI Agent Activity</span>
                <ViewAll />
              </div>
              <div className="mt-2 space-y-1.5">
                {agents.map((a) => (
                  <div key={a.who} className="flex items-center gap-2">
                    <span className="grid h-6 w-6 shrink-0 place-items-center rounded-full text-[8px] font-bold" style={{ background: `${a.color}26`, color: a.color }}>
                      {a.who.replace("AI ", "").slice(0, 2)}
                    </span>
                    <div className="min-w-0 flex-1 leading-tight">
                      <div className="truncate text-[9.5px] font-semibold text-foreground">{a.who}</div>
                      <div className="truncate text-[8.5px] text-muted">{a.act}</div>
                    </div>
                    <span className="whitespace-nowrap text-[8.5px] text-muted">{a.time}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* row 2 */}
          <div className="mt-3 grid gap-3 sm:grid-cols-3">
            {/* modules */}
            <div className="rounded-xl border border-card-border bg-card-2/50 p-3">
              <div className="flex items-center justify-between">
                <span className="text-[10.5px] font-semibold text-foreground">Modules</span>
                <ViewAll />
              </div>
              <div className="mt-2 space-y-1.5">
                {modules.map((mm) => (
                  <div key={mm.name}>
                    <div className="flex justify-between text-[8.5px]">
                      <span className="truncate text-foreground/75">{mm.name}</span>
                      <span className="text-muted">{mm.value}%</span>
                    </div>
                    <div className="mt-0.5 h-1 w-full overflow-hidden rounded-full bg-foreground/10">
                      <div className="h-full rounded-full" style={{ width: `${mm.value}%`, background: mm.color }} />
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* sprint progress */}
            <div className="rounded-xl border border-card-border bg-card-2/50 p-3">
              <div className="flex items-center justify-between">
                <span className="text-[10.5px] font-semibold text-foreground">Sprint Progress</span>
                <span className="rounded bg-brand/15 px-1.5 py-0.5 text-[7.5px] font-semibold text-brand">Current Sprint</span>
              </div>
              <div className="mt-2 flex items-center justify-between text-[8.5px]">
                <span className="text-foreground/75">Sprint 7 (May 1 - May 15)</span>
                <span className="font-semibold text-foreground">65%</span>
              </div>
              <div className="mt-1 h-1.5 w-full overflow-hidden rounded-full bg-foreground/10">
                <div className="h-full w-[65%] rounded-full bg-gradient-to-r from-brand to-accent" />
              </div>
              <div className="mt-3 grid grid-cols-3 gap-1 text-center">
                {[["32", "Total"], ["21", "Completed"], ["11", "In Progress"]].map(([v, l]) => (
                  <div key={l}>
                    <div className="text-[15px] font-bold text-foreground">{v}</div>
                    <div className="text-[7.5px] text-muted">{l}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* recent artifacts */}
            <div className="rounded-xl border border-card-border bg-card-2/50 p-3">
              <div className="text-[10.5px] font-semibold text-foreground">Recent Artifacts</div>
              <div className="mt-2 space-y-1.5">
                {artifacts.map((a) => (
                  <div key={a.name} className="flex items-center gap-1.5">
                    <span className="grid h-5 w-5 shrink-0 place-items-center rounded-md bg-brand/15 text-brand">
                      <a.icon size={10} />
                    </span>
                    <span className="min-w-0 flex-1 truncate text-[8.5px] font-medium text-foreground/80">{a.name}</span>
                    <span className="rounded bg-foreground/10 px-1 py-0.5 text-[7px] text-muted">{a.ver}</span>
                    <span className="whitespace-nowrap text-[7.5px] text-muted">{a.time}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

/* ─────────────────────────── section ─────────────────────────── */
export function Features() {
  return (
    <section className="relative overflow-hidden py-20 sm:py-28">
      <div className="bg-grid pointer-events-none absolute inset-0 opacity-[0.2] [mask-image:radial-gradient(ellipse_at_center,black,transparent_75%)]" />
      <div className="pointer-events-none absolute right-0 top-1/4 h-[460px] w-[700px] rounded-full bg-[radial-gradient(ellipse_at_center,var(--glow),transparent_70%)] blur-3xl" />

      <div className="relative mx-auto max-w-[1600px] px-5 sm:px-8 lg:px-10">
        {/* header */}
        <motion.div
          variants={fade}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true, margin: "-80px" }}
          transition={{ duration: 0.6 }}
          className="mx-auto max-w-3xl text-center"
        >
          <span className="inline-flex items-center rounded-full border border-brand/30 bg-brand/10 px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.14em] text-brand">
            Powerful Features
          </span>
          <h2 className="mt-5 text-4xl font-bold leading-[1.1] tracking-tight text-foreground sm:text-5xl">
            Everything You Need To Build
            <br />
            Great Products, <span className="brand-gradient-text">Faster</span>
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-muted">
            Operixa brings your entire product development lifecycle into one
            intelligent workspace. From idea to production—every artifact, every
            step, perfectly connected.
          </p>
        </motion.div>

        {/* features + dashboard — equal height columns */}
        <div className="mt-14 grid items-stretch gap-8 lg:grid-cols-[1fr_1.12fr] lg:gap-8">
          {/* feature grid */}
          <div className="grid gap-4 sm:grid-cols-2 lg:h-full lg:auto-rows-fr">
            {features.map((feat, i) => (
              <motion.div
                key={feat.title}
                variants={fade}
                initial="hidden"
                whileInView="show"
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.45, delay: (i % 2) * 0.05 }}
                className="group rounded-2xl border border-white/10 bg-card/60 p-5 backdrop-blur-xl transition-all hover:-translate-y-1 hover:border-brand/40 hover:shadow-[0_18px_50px_-24px_var(--glow)]"
              >
                <span className="grid h-11 w-11 place-items-center rounded-xl bg-gradient-to-br from-violet-500 to-blue-500 text-white shadow-[0_0_24px_-8px_var(--brand)]">
                  <feat.icon size={20} />
                </span>
                <h3 className="mt-4 text-sm font-semibold text-foreground">{feat.title}</h3>
                <p className="mt-1.5 text-xs leading-relaxed text-muted">{feat.desc}</p>
              </motion.div>
            ))}
          </div>

          {/* dashboard mockup + pills */}
          <motion.div
            variants={fade}
            initial="hidden"
            whileInView="show"
            viewport={{ once: true, margin: "-50px" }}
            transition={{ duration: 0.6 }}
            className="flex flex-col gap-5"
          >
            <div className="min-h-[420px] flex-1">
              <DashboardMock />
            </div>
            <div className="flex flex-wrap justify-center gap-2">
              {pills.map((p) => (
                <span
                  key={p.label}
                  className="inline-flex items-center gap-1.5 rounded-full border border-card-border bg-card/60 px-3 py-1.5 text-xs text-muted backdrop-blur"
                >
                  <p.icon size={13} className="text-brand" />
                  {p.label}
                </span>
              ))}
            </div>
          </motion.div>
        </div>

        {/* bottom banner */}
        <motion.div
          variants={fade}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true, margin: "-60px" }}
          transition={{ duration: 0.6 }}
          className="relative mt-16 overflow-hidden rounded-3xl border border-brand/25 bg-card/60 p-6 backdrop-blur-xl sm:p-8"
        >
          <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_left,var(--glow),transparent_60%)]" />
          <div className="relative flex flex-col items-center gap-8 lg:flex-row lg:justify-between">
            <div className="flex items-center gap-5">
              <Image src="/cube-dark2.png" alt="" width={120} height={120} className="hidden h-16 w-16 shrink-0 dark:block" />
              <Image src="/cube-light1.png" alt="" width={120} height={120} className="block h-16 w-16 shrink-0 mix-blend-multiply dark:hidden" />
              <div className="text-center lg:text-left">
                <h3 className="text-xl font-bold text-foreground sm:text-2xl">
                  One Workspace. Everything Connected.
                </h3>
                <p className="mt-2 max-w-md text-sm text-muted">
                  No more scattered tools. No more context switching. Operixa
                  brings your entire product development journey into one
                  intelligent, unified workspace.
                </p>
              </div>
            </div>
            <div className="flex shrink-0 gap-6 sm:gap-10">
              {stats.map((s) => (
                <div key={s.label} className="text-center">
                  <s.icon size={22} className="mx-auto text-brand" />
                  <div className="mt-2 text-2xl font-bold brand-gradient-text sm:text-3xl">{s.value}</div>
                  <div className="mt-0.5 text-xs text-muted">{s.label}</div>
                </div>
              ))}
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
